### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by firmianay** [stacscan/stacs#16]
```
$ pip --version    
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
$ pip install stacs
ERROR: Could not find a version that satisfies the requirement stacs (from versions: none)
ERROR: No matching distribution found for stacs
```

**Comment by darkarnium** [comment]
Hey there,

Thanks for the report! Can you let me know which operating system / distribution you're using so that I can try and reproduce? I think I know what's causing this :)

**Comment by firmianay** [comment]
Hi, I noticed that setup.cfg shows that the minimum python version is 3.9, which may be the reason, but I doubt that such a high version is really needed?
```
$ uname -a
Linux firmy-pc 5.13.0-32-generic #35~20.04.1-Ubuntu SMP Thu Feb 24 15:42:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by darkarnium** [comment]
Hey there,

I'll review my development notes, but STACS **should** be compatible with Python 3.8. 

From what I recall the requirement being set to Python 3.9 was due to performance improvements seen in local benchmarks versus 3.8. That said, if there is no incompatibility then this can just be a mentioned as a note in the documentation that Python 3.9 may result in performance improvements. That said, I'll regenerate these benchmarks to confirm.

Let me run some regression tests against 3.8 and publish a new build with the version constraint set to 3.8 if there are no incompatibilities.

Thanks again for the report!

**Comment by darkarnium** [comment]
Hey there,

Sorry this took so long, I had to make some changes to release management so that I could publish a candidate to PyPi testing to validate that the new package is compatible with Python >= 3.8.

I've included validation that STACS can be installed under Python 3.8 below, but you should be able to install directly from production PyPI now that the new release has been cut:

* https://github.com/stacscan/stacs/releases/tag/0.4.5

**Validation:**
```
$ python3.8 -m venv env
$ source env/bin/activate
$ pip install stacs
ERROR: Could not find a version that satisfies the requirement stacs (from versions: none)
ERROR: No matching distribution found for stacs

# New package from PyPI testing.
$ pip install -i https://test.pypi.org/simple/ stacs==0.4.5.dev4 --no-deps
Looking in indexes: https://test.pypi.org/simple/
...
Installing collected packages: stacs
Successfully installed stacs-0.4.5.dev4
```

Please let me know if this has resolved this issue, and I'll close out this issue.

Thanks again for your report!

**Comment by firmianay** [comment]
The installation was successful, thank you very much.
